version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase  # Замените на ваши данные
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mydatabase  # Имя вашей базы данных
      POSTGRES_USER: postgres   # Имя пользователя базы данных
      POSTGRES_PASSWORD: password # Пароль пользователя базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: